language: objective-c
matrix:
  include:
    - os: osx
      osx_image: xcode9.1
    - os: osx
      osx_image: xcode8.3
cache:
  bundler: true
  cocoapods: true
  directories: []
branches:
  only:
    - travis
    - dev
    - release
    - master
before_install:
  - curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  - rvm get latest --auto-dotfiles
  - rvm use 2.4 --default --install --binary --fuzzy
  - (ruby --version)
  - sudo motion update
  - (motion --version)
script:
  - bundle exec rake pod:install
  - bundle exec rake clean spec device_name='iPhone X' output=tap
