language: objective-c
osx_image: xcode8.3
branches:
  only:
    - travis
    - dev
    - release
    - master
before_install:
  - sudo motion update
  - rvm get stable --auto-dotfiles
  - rvm use 2.4 --install --binary --fuzzy
  - (ruby --version)
gemfile:
  - Gemfile
script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake pod:install
  - bundle exec rake clean
  - bundle exec rake spec
