language: objective-c
osx_image: xcode8.3
branches:
  only:
    - travis
    - dev
    - release
    - master
before_install:
  - gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - rvm get stable --auto-dotfiles
  - rvm use 2.4 --install --binary --fuzzy
  - (ruby --version)
  - sudo motion update
gemfile:
  - Gemfile
script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake pod:install
  - bundle exec rake clean
  - bundle exec rake spec
